# server:
#   address: 0.0.0.0
#   port: 8080
#   compression:
#     enabled: true
# spring:
#   jpa:
#     hibernate:
#       ddl-auto: update
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.PostgreSQLDialect
#   datasource:
#     driver-class-name: org.postgresql.Driver
#     url: jdbc:postgresql://localhost:5432/pa
#     username: postgres
#     password: root
#     hikari:
#       connection-timeout: 30000
#       minimum-idle: 1
#       maximum-pool-size: 5
#       idle-timeout: 60000
#       max-lifetime: 1800000
#       pool-name: pa-hikari-pool
#   servlet:
#     multipart:
#       max-file-size: 10MB
#       max-request-size: 10MB
#       location: src/main/resources/files/
# application:
#   security:
#     jwt:
#       secret-key: 719650a6094eb3d68b1765ef97d1400bdf12cde09874681b351346225c90c5f6
#       expiration: 86400000
#       refresh-token:
#         expiration: 604800000

# ******************************* Paramettre docker ********************** 

server:
  address: 0.0.0.0
  port: 8080
  compression:
    enabled: true
spring:
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      connection-timeout: 30000
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 60000
      max-lifetime: 1800000
      pool-name: pa-hikari-pool
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: src/main/resources/files/
application:
  security:
    jwt:
      secret-key: 719650a6094eb3d68b1765ef97d1400bdf12cde09874681b351346225c90c5f6
      expiration: 86400000
      refresh-token:
        expiration: 604800000

